services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "2000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - cclemon-network
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - cclemon-network
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
      - "4317:4317"
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
    command: -config.file=/etc/tempo.yaml
    networks:
      - cclemon-network
    restart: unless-stopped

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "9009:9009"
    networks:
      - cclemon-network
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"  # optional Alloy web interface
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /path/to/your/logs:/var/log  # <-- 修改為實際 log 資料夾
    networks:
      - cclemon-network
    restart: unless-stopped

volumes:
  grafana-storage: {}

networks:
  cclemon-network:
    external: true
