server:
  http_listen_port: 3200
  grpc_listen_port: 4317

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
