services:
  jenkins:
    build: .
    image: jenkins
    container_name: jenkins
    ports:
      - "3000:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home/init.groovy.d:/usr/share/jenkins/ref/init.groovy.d
      - ./jenkins_home/jobs:/var/jenkins_home/jobs
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - cclemon-network
    privileged: true

volumes:
  jenkins_home:

networks:
  cclemon-network:
    external: true