apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
spec:
  selector:
    app: redis-commander
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081  # 外部可透過這個 port 存取
  type: NodePort