version: '3.8'

services:
  kafka1:
    container_name: kafka1
    image: bitnami/kafka:3.9
    ports:
      - "9093:9093" # 對外可用
    volumes:
      - kafka_data1:/bitnami
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=my-kafka-cluster_id
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9094,1@kafka2:9094,2@kafka3:9094
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL://localhost:9093,CONTROLLER://kafka1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks:
      - cclemon-network

  kafka2:
    container_name: kafka2
    image: bitnami/kafka:3.9
    ports:
      - "9095:9093"
    volumes:
      - kafka_data2:/bitnami
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=my-kafka-cluster_id
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9094,1@kafka2:9094,2@kafka3:9094
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,EXTERNAL://localhost:9095,CONTROLLER://kafka2:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks:
      - cclemon-network

  kafka3:
    container_name: kafka3
    image: bitnami/kafka:3.9
    ports:
      - "9097:9093"
    volumes:
      - kafka_data3:/bitnami
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=my-kafka-cluster_id
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9094,1@kafka2:9094,2@kafka3:9094
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9092,EXTERNAL://localhost:9097,CONTROLLER://kafka3:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks:
      - cclemon-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8882:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092,kafka2:9092,kafka3:9092
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - cclemon-network

  kafka-connect:
    container_name: kafka-connect
    image: debezium/connect:2.7.3.Final  # 使用 Debezium Kafka Connect 版本，或可以選擇其他版本
    environment:
      - GROUP_ID=connect-cluster
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
      - CONNECT_PLUGIN_PATH=/usr/share/java/kafka-connect
    volumes:
      - ./libs:/usr/share/java/kafka-connect  # 確保 JAR 文件放在此路徑
      - ./data:/data
    ports:
      - "8083:8083"  # Kafka Connect REST API 端口
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - cclemon-network

volumes:
  kafka_data1:
    driver: local
  kafka_data2:
    driver: local
  kafka_data3:
    driver: local

networks:
  cclemon-network:
    external: true
