version: '3.8'

services:
  redis:
    image: docker.io/bitnami/redis:8.0
    container_name: redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - cclemon-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    ports:
      - '8081:8081'
    environment:
      REDIS_HOSTS: local:redis:6379
    networks:
      - cclemon-network

volumes:
  redis_data:
    driver: local

networks:
  cclemon-network:
    external: true